import typing
from decimal import Decimal

from typing_extensions import Literal
import pydantic
import stackprinter
stackprinter.set_excepthook(style="darkbg2")

from crypto_dom.definitions import TIMESTAMP_MS
from crypto_dom.binance.definitions import OCO_ORDER_STATUS, OCO_STATUS, ORDER_SIDE, ORDER_STATUS, ORDER_TYPE, ORDER_TIF, RECV_WINDOW, SYMBOL


# ============================================================
# CANCEL OCO (TRADE)
# ============================================================


# doc: https://binance-docs.github.io/apidocs/spot/en/#cancel-oco-trade

URL = "https://api.binance.com/api/v3/orderList"
METHOD = "DELETE"
WEIGHT = 1


# ------------------------------
# Sample Response (doc)
# ------------------------------


# {
#   "orderListId": 0,
#   "contingencyType": "OCO",
#   "listStatusType": "ALL_DONE",
#   "listOrderStatus": "ALL_DONE",
#   "listClientOrderId": "C3wyj4WVEktd7u9aVBRXcN",
#   "transactionTime": 1574040868128,
#   "symbol": "LTCBTC",
#   "orders": [
#     {
#       "symbol": "LTCBTC",
#       "orderId": 2,
#       "clientOrderId": "pO9ufTiFGg3nw2fOdgeOXa"
#     },
#     {
#       "symbol": "LTCBTC",
#       "orderId": 3,
#       "clientOrderId": "TXOvglzXuaubXAaENpaRCB"
#     }
#   ],
#   "orderReports": [
#     {
#       "symbol": "LTCBTC",
#       "origClientOrderId": "pO9ufTiFGg3nw2fOdgeOXa",
#       "orderId": 2,
#       "orderListId": 0,
#       "clientOrderId": "unfWT8ig8i0uj6lPuYLez6",
#       "price": "1.00000000",
#       "origQty": "10.00000000",
#       "executedQty": "0.00000000",
#       "cummulativeQuoteQty": "0.00000000",
#       "status": "CANCELED",
#       "timeInForce": "GTC",
#       "type": "STOP_LOSS_LIMIT",
#       "side": "SELL",
#       "stopPrice": "1.00000000"
#     },
#     {
#       "symbol": "LTCBTC",
#       "origClientOrderId": "TXOvglzXuaubXAaENpaRCB",
#       "orderId": 3,
#       "orderListId": 0,
#       "clientOrderId": "unfWT8ig8i0uj6lPuYLez6",
#       "price": "3.00000000",
#       "origQty": "10.00000000",
#       "executedQty": "0.00000000",
#       "cummulativeQuoteQty": "0.00000000",
#       "status": "CANCELED",
#       "timeInForce": "GTC",
#       "type": "LIMIT_MAKER",
#       "side": "SELL"
#     }
#   ]
# }


# ------------------------------
# Request Model
# ------------------------------


class Request(pydantic.BaseModel):
    """Request model for endpoint POST https://api.binance.com/api/v3/orderList
    
    Model Fields:
    -------------
        symbol : str
        orderListId: int
            (optional)
        listClientOrderId: str
            A unique Id for the entire orderList (optional)
        newClientOrderId: str
            Used to uniquely identify this cancel (optional)
            Automatically generated by default 
        timestamp : float
        recvWindow : int
           Number of milliseconds after timestamp the request is valid for (optional)
           Default = 5000

    Note:
    -----
        Canceling an individual leg will cancel the entire OCO
    """

    symbol: SYMBOL
    orderListId: typing.Optional[int]
    listClientOrderId: typing.Optional[str]
    newClientOrderId: typing.Optional[str] 

    timestamp: TIMESTAMP_MS
    recvWindow: typing.Optional[RECV_WINDOW]
    
    
    @pydantic.validator("listClientOrderId")
    def _check_mandatory_args(cls, v, values):

        if v is None:
            if values.get("orderListId") is None:
                raise ValueError("Either orderListId or listClientOrderId must be provided")

        return v


# ------------------------------
# Response Model
# ------------------------------


class _Order(pydantic.BaseModel):
    symbol: SYMBOL
    orderId: pydantic.PositiveInt
    clientOrderId: str


class _OrderReport(pydantic.BaseModel):
    symbol: SYMBOL
    origClientOrderId: str
    orderId: pydantic.PositiveInt
    orderListId: int 
    clientOrderId: str
    price: Decimal
    origQty: Decimal
    executedQty: Decimal
    cummulativeQuoteQty: Decimal
    status: ORDER_STATUS
    timeInForce: ORDER_TIF
    type: ORDER_TYPE
    side: ORDER_SIDE
    stopPrice: typing.Optional[Decimal]


class _CancelOCOResp(pydantic.BaseModel):

    orderListId: int
    contingencyType: Literal["OCO"]     # TODO add rest of enums
    listStatusType: OCO_STATUS
    listOrderStatus: OCO_ORDER_STATUS
    listClientOrderId: str
    transactionTime: TIMESTAMP_MS
    symbol: SYMBOL
    orders: typing.Tuple[_Order, ...]
    orderReports: typing.Tuple[_OrderReport, ...]



#  this class is just to be consistent with our API
class Response:
    """Validated Response for endpoint POST https://api.binance.com/api/v3/orderList

    Type: pydantic Model 

    Model Fields:
    -------------
        orderListId: int
        contigencyType: str enum
        listStatusType: str enum
        listOrderStatus: str enum
        listClientOrderId: str enum
        transactionTime: float
            Timestamp in milliseconds
        symbol: str
        orders: Tuple[pydantic.BaseModel]
        orderReports: Tuple[pydantic.BaseModel]
    """

    def __new__(_cls):
        return _CancelOCOResp
        
   
    



if __name__ == "__main__":
  
    data = {
  "orderListId": 0,
  "contingencyType": "OCO",
  "listStatusType": "ALL_DONE",
  "listOrderStatus": "ALL_DONE",
  "listClientOrderId": "C3wyj4WVEktd7u9aVBRXcN",
  "transactionTime": 1574040868128,
  "symbol": "LTCBTC",
  "orders": [
    {
      "symbol": "LTCBTC",
      "orderId": 2,
      "clientOrderId": "pO9ufTiFGg3nw2fOdgeOXa"
    },
    {
      "symbol": "LTCBTC",
      "orderId": 3,
      "clientOrderId": "TXOvglzXuaubXAaENpaRCB"
    }
  ],
  "orderReports": [
    {
      "symbol": "LTCBTC",
      "origClientOrderId": "pO9ufTiFGg3nw2fOdgeOXa",
      "orderId": 2,
      "orderListId": 0,
      "clientOrderId": "unfWT8ig8i0uj6lPuYLez6",
      "price": "1.00000000",
      "origQty": "10.00000000",
      "executedQty": "0.00000000",
      "cummulativeQuoteQty": "0.00000000",
      "status": "CANCELED",
      "timeInForce": "GTC",
      "type": "STOP_LOSS_LIMIT",
      "side": "SELL",
      "stopPrice": "1.00000000"
    },
    {
      "symbol": "LTCBTC",
      "origClientOrderId": "TXOvglzXuaubXAaENpaRCB",
      "orderId": 3,
      "orderListId": 0,
      "clientOrderId": "unfWT8ig8i0uj6lPuYLez6",
      "price": "3.00000000",
      "origQty": "10.00000000",
      "executedQty": "0.00000000",
      "cummulativeQuoteQty": "0.00000000",
      "status": "CANCELED",
      "timeInForce": "GTC",
      "type": "LIMIT_MAKER",
      "side": "SELL"
    }
  ]
}

    model = Response()
    model(**data)