import typing
from decimal import Decimal

import pydantic
import stackprinter
stackprinter.set_excepthook(style="darkbg2")

from crypto_dom.definitions import TIMESTAMP_MS
from crypto_dom.binance.definitions import  ORDER_SIDE, ORDER_STATUS, ORDER_TYPE, ORDER_TIF, RECV_WINDOW, SYMBOL


# ============================================================
# CANCEL ORDER (TRADE)
# ============================================================


# doc: https://binance-docs.github.io/apidocs/spot/en/#cancel-order-trade

URL = "https://api.binance.com/api/v3/order"
METHOD = "DELETE"
WEIGHT = 1


# ------------------------------
# Sample Response (doc)
# ------------------------------


# {
#   "symbol": "LTCBTC",
#   "origClientOrderId": "myOrder1",
#   "orderId": 4,
#   "orderListId": -1, //Unless part of an OCO, the value will always be -1.
#   "clientOrderId": "cancelMyOrder1",
#   "price": "2.00000000",
#   "origQty": "1.00000000",
#   "executedQty": "0.00000000",
#   "cummulativeQuoteQty": "0.00000000",
#   "status": "CANCELED",
#   "timeInForce": "GTC",
#   "type": "LIMIT",
#   "side": "BUY"
# }


# ------------------------------
# Request Model
# ------------------------------


class Request(pydantic.BaseModel):
    """Request model for endpoint DELETE https://api.binance.com/api/v3/order

    Model Fields:
    -------------
        symbol : str
        orderId : int
            (optional)
        origClientOrderId : str
            (optional)
        newClientOrderId : str
            Used to uniquely identify this cancel. Automatically generated by default.
            (optional)

        timestamp : float
        recvWindow : int
           Number of milliseconds after timestamp the request is valid for (optional)
           Default = 5000

    """

    symbol: SYMBOL
    orderId: typing.Optional[int]
    origClientOrderId: typing.Optional[str]
    newClientOrderId: typing.Optional[str]

    timestamp: TIMESTAMP_MS
    recvWindow: typing.Optional[RECV_WINDOW]


    @pydantic.validator("origClientOrderId")
    def _check_mandatory_args(cls, v, values):

        if v is None:
            if values.get("orderId") is None:
                raise ValueError("Either orderId or origClientOrderId must be sent")

        return v


# ------------------------------
# Response Model
# ------------------------------


class _CancelOrderResp(pydantic.BaseModel):

    symbol: SYMBOL
    origClientOrderId: str
    orderId: pydantic.PositiveInt
    orderListId: pydantic.conint(ge=-1)
    clientOrderId: str
    price: Decimal
    origQty: Decimal
    executedQty: Decimal
    cummulativeQuoteQty: Decimal
    status: ORDER_STATUS
    timeInForce: ORDER_TIF
    type: ORDER_TYPE
    side: ORDER_SIDE


#  this class is just to be consistent with our API
class Response:
    """Validated Response for endpoint DELETE https://api.binance.com/api/v3/order

    Type: pydantic.BaseModel

    Model Fields:
    -------------
        symbol: str
        origClientOrderId: str
        orderId: int
        orderListId: int
            Unless part of an OCO, the value will always be -1
        clientOrderId: str
        price: Decimal
        origQty: Decimal
        executedQty: Decimal
        cummulativeQuoteQty: Decimal
        status: str enum
        timeInForce: str enum
        type: str enum
        side: str enum

    """

    def __new__(_cls):
        return _CancelOrderResp 
       


if __name__ == "__main__":
    data = {
  "symbol": "LTCBTC",
  "origClientOrderId": "myOrder1",
  "orderId": 4,
  "orderListId": -1,
  "clientOrderId": "cancelMyOrder1",
  "price": "2.00000000",
  "origQty": "1.00000000",
  "executedQty": "0.00000000",
  "cummulativeQuoteQty": "0.00000000",
  "status": "CANCELED",
  "timeInForce": "GTC",
  "type": "LIMIT",
  "side": "BUY"
}

    model = Response()
    model(**data)